-- Base app schema


-- User
-- NOTE: Jeremy likes to start at ID=1000 to reserve the first batch
-- for test users, root users, etc. Just a practice.
CREATE TABLE "user"(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  username varchar(128) NOT NULL UNIQUE
);



-- Task
CREATE TABLE task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  title varchar(256) NOT NULL
);


