-- Base app schema


-- User
-- NOTE: Jeremy likes to start at ID=1000 to reserve the first batch
-- for test users, root users, etc. Just a practice.
CREATE TABLE "user"(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  username varchar(128) NOT NULL UNIQUE,

  -- Auth
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid()
);



-- Task
CREATE TABLE task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  title varchar(256) NOT NULL,
  -- NOTE: TIP! - Usually it's good to avoid null values in a db,
  -- so booleans help or even DB enums for three-state properties.
  done bool NOT NULL DEFAULT false
);


-- Token
CREATE TABLE token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  update_unix_time BIGINT NOT NULL,
  update_human_time TEXT NOT NULL,
  mint_address TEXT NOT NULL,
  decimals BIGINT NOT NULL,
  symbol TEXT NOT NULL,
  name TEXT NOT NULL,
  mc DOUBLE PRECISION NOT NULL,
  v24h_change_percent DOUBLE PRECISION NOT NULL,
  v24h_usd DOUBLE PRECISION NOT NULL
);
